/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3EFACEBOOKTRACKING_AUTODEFS_H
#define S3EFACEBOOKTRACKING_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_FACEBOOKTRACKING_NAME "s3eFacebookTracking"
#define S3E_EXT_FACEBOOKTRACKING_HASH 0x3957d59d

#endif /* !S3EFACEBOOKTRACKING_AUTODEFS_H */
